/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdhcuoiky;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import shapes2d.DoanThang;
import shapes2d.HinhChuNhat;
import shapes2d.HinhTron;

/**
 *
 * @author COMPUTER
 */
public class MainFrame extends javax.swing.JFrame {
    public final static int UNIT = 30;
    public final static int PIXEL_SIZE = 5;
    public static int maxX, maxY;
    public static int midX, midY;
    public BufferedImage offImage;
    public Graphics2D g2d;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        maxX = jPanel2D.getWidth();
        maxY = jPanel2D.getHeight();
        System.out.println(maxX + " " + maxY);
        midX = maxX / 2;
        midY = maxY / 2;
        System.out.println(midX + " " + midY);
        offImage = new BufferedImage(maxX, maxY, BufferedImage.TYPE_INT_ARGB);
        g2d = offImage.createGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2D = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(offImage, 0, 0, null);
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxShape = new javax.swing.JComboBox<>();
        jPanelCard = new javax.swing.JPanel();
        jPanelLineAndRectCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldX1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldY1 = new javax.swing.JTextField();
        jTextFieldX2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldY2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelCircleCard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelXC = new javax.swing.JLabel();
        jTextFieldXC = new javax.swing.JTextField();
        jLabelYC = new javax.swing.JLabel();
        jTextFieldYC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelR = new javax.swing.JLabel();
        jTextFieldR = new javax.swing.JTextField();
        jPanelEllipseCard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonDraw = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jCheckBoxGridMode = new javax.swing.JCheckBox();
        jCheckBoxCoordSystem = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2DLayout = new javax.swing.GroupLayout(jPanel2D);
        jPanel2D.setLayout(jPanel2DLayout);
        jPanel2DLayout.setHorizontalGroup(
            jPanel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel2DLayout.setVerticalGroup(
            jPanel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chọn hình vẽ");

        jComboBoxShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đoạn thẳng", "Hình chữ nhật", "Hình tròn", "Hình Ellipse" }));
        jComboBoxShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShapeActionPerformed(evt);
            }
        });

        jPanelCard.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tọa độ điểm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("x1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("y1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("x2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("y2");

        javax.swing.GroupLayout jPanelLineAndRectCardLayout = new javax.swing.GroupLayout(jPanelLineAndRectCard);
        jPanelLineAndRectCard.setLayout(jPanelLineAndRectCardLayout);
        jPanelLineAndRectCardLayout.setHorizontalGroup(
            jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 115, Short.MAX_VALUE))
            .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldY1))
                    .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX2))
                    .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldY2)))
                .addContainerGap())
        );
        jPanelLineAndRectCardLayout.setVerticalGroup(
            jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelLineAndRectCard, "cardLineAndRect");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tọa độ tâm");

        jLabelXC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelXC.setText("x");

        jLabelYC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelYC.setText("y");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bán kính");

        jLabelR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelR.setText("r");

        javax.swing.GroupLayout jPanelCircleCardLayout = new javax.swing.GroupLayout(jPanelCircleCard);
        jPanelCircleCard.setLayout(jPanelCircleCardLayout);
        jPanelCircleCardLayout.setHorizontalGroup(
            jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                        .addComponent(jLabelXC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldXC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                        .addComponent(jLabelYC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldYC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                        .addComponent(jLabelR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelCircleCardLayout.setVerticalGroup(
            jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXC)
                    .addComponent(jTextFieldXC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYC)
                    .addComponent(jTextFieldYC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR)
                    .addComponent(jTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelCircleCard, "cardCircle");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tọa độ tâm");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("a");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("x");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("y");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Bán kính");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("b");

        javax.swing.GroupLayout jPanelEllipseCardLayout = new javax.swing.GroupLayout(jPanelEllipseCard);
        jPanelEllipseCard.setLayout(jPanelEllipseCardLayout);
        jPanelEllipseCardLayout.setHorizontalGroup(
            jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEllipseCardLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEllipseCardLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelEllipseCardLayout.setVerticalGroup(
            jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelEllipseCard, "cardEllipse");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Chức năng");

        jButtonDraw.setText("Vẽ");
        jButtonDraw.setToolTipText("");
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrawActionPerformed(evt);
            }
        });

        jButtonClear.setText("Xóa");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Chế độ");

        jCheckBoxGridMode.setText("Lưới pixels");
        jCheckBoxGridMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGridModeActionPerformed(evt);
            }
        });

        jCheckBoxCoordSystem.setText("Trục tọa độ");
        jCheckBoxCoordSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoordSystemActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Animation");

        jButton3.setText("Animation 1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxShape, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButtonDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jCheckBoxGridMode, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jCheckBoxCoordSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxShape, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDraw)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGridMode)
                    .addComponent(jCheckBoxCoordSystem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("2D", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("3D", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean lackInformation() {
        String x1 = jTextFieldX1.getText();
        String y1 = jTextFieldY1.getText();
        String x2 = jTextFieldX2.getText();
        String y2 = jTextFieldY2.getText();
        return x1.equals("") || x2.equals("") || y1.equals("") || y2.equals("");
    }
    public boolean lackInformationAboutCircle() {
        String xC = jTextFieldXC.getText();
        String yC = jTextFieldYC.getText();
        String r = jTextFieldR.getText();
        return xC.equals("") || yC.equals("") || r.equals("");
    }
    
    public void drawPixelGrid(Graphics2D g2d) {
        g2d.setColor(Color.LIGHT_GRAY);
        for (int i = 5; i < maxX; i += PIXEL_SIZE) {
            g2d.drawLine(i, 0, i, maxY);
        }
        for (int i = 5; i < maxY; i += PIXEL_SIZE) {
            g2d.drawLine(0, i, maxX, i);
        }
    }
    public void drawCoordinateSystem(Graphics2D g2d) {
        g2d.setColor(Color.BLACK);
        g2d.drawLine(0, midY, maxX, midY); // draw x axis
        g2d.drawLine(midX, 0, midX, maxY); // draw y axis
        g2d.setFont(new Font("Tahoma", Font.BOLD, 12));
        g2d.drawString("X", maxX - 20, midY - 10);
        g2d.drawString("Y", midX + 10, 20);
        g2d.drawString("O", midX - 15, midY + 15);

        g2d.setFont(new Font("Tahoma", Font.PLAIN, 11));
        // danh so don vi 1, 2, 3, 4, 5... truc Ox
        for (int i = midX + UNIT; i < maxX; i += UNIT) {
            g2d.drawLine(i, midY - 2, i, midY + 2);
            g2d.drawString(String.valueOf((i - midX) / 30), i - 4, midY + 15);
        }
        for (int i = midX - UNIT; i > 0; i -= UNIT) {
            g2d.drawLine(i, midY - 2, i, midY + 2);
            //            g.drawString(String.valueOf((i - midX) / 30), i - 4, midY + 15);
        }

        // danh so don vi 1, 2, 3, 4, 5... truc Oy
        for (int i = midY - UNIT; i > 0; i -= UNIT) {
            g2d.drawLine(midX - 2, i, midX + 2, i);
            g2d.drawString(String.valueOf((midY - i) / 28), midX - 20, i + 4);
        }
        for (int i = midY + UNIT; i < maxY; i += UNIT) {
            g2d.drawLine(midX - 2, i, midX + 2, i);
            //            g.drawString(String.valueOf((midY - i) / 30), midX - 20, i + 4);
        }
    }
    private void jCheckBoxGridModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGridModeActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxGridMode.isSelected()) {
            drawPixelGrid(g2d);
        } else {
            g2d.setBackground(new Color(255, 255, 255, 0));
            g2d.clearRect(0, 0, maxX, maxY);
            if (jCheckBoxCoordSystem.isSelected()) {
                drawCoordinateSystem(g2d);
            }
        }
        jPanel2D.repaint();
    }//GEN-LAST:event_jCheckBoxGridModeActionPerformed

    private void jCheckBoxCoordSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCoordSystemActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxCoordSystem.isSelected()) {
            drawCoordinateSystem(g2d);
        } else {
            g2d.setBackground(new Color(255, 255, 255, 0));
            g2d.clearRect(0, 0, maxX, maxY);
            if (jCheckBoxGridMode.isSelected()) {
                drawPixelGrid(g2d);
            }
        }
        jPanel2D.repaint();
    }//GEN-LAST:event_jCheckBoxCoordSystemActionPerformed

    private void jButtonDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrawActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBoxShape.getSelectedItem();
        g2d.setColor(Color.BLACK);
        if (selectedItem.equals("Đoạn thẳng")) {
            if (!lackInformation()) {
                int x1 = midX + Integer.parseInt(jTextFieldX1.getText()) * UNIT;
                int y1 = midY - Integer.parseInt(jTextFieldY1.getText()) * UNIT;
                int x2 = midX + Integer.parseInt(jTextFieldX2.getText()) * UNIT;
                int y2 = midY - Integer.parseInt(jTextFieldY2.getText()) * UNIT;
                new DoanThang().draw(x1, y1, x2, y2, g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        } else if (selectedItem.equals("Hình chữ nhật")) {
            if (!lackInformation()) {
                int x1 = midX + Integer.parseInt(jTextFieldX1.getText()) * UNIT;
                int y1 = midY - Integer.parseInt(jTextFieldY1.getText()) * UNIT;
                int x2 = midX + Integer.parseInt(jTextFieldX2.getText()) * UNIT;
                int y2 = midY - Integer.parseInt(jTextFieldY2.getText()) * UNIT;
                new HinhChuNhat().draw(new Point(x1, y1), new Point(x2, y2), g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        } else if (selectedItem.equals("Hình tròn")) {
            if (!lackInformationAboutCircle()) {
                int xC = midX + Integer.parseInt(jTextFieldXC.getText()) * UNIT;
                int yC = midY - Integer.parseInt(jTextFieldYC.getText()) * UNIT;
                int r = Integer.parseInt(jTextFieldR.getText()) * UNIT;
                new HinhTron().draw(xC, yC, r, g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        }
    }//GEN-LAST:event_jButtonDrawActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        g2d.setBackground(new Color(255, 255, 255, 0));
        g2d.clearRect(0, 0, maxX, maxY);
        if (jCheckBoxGridMode.isSelected()) {
            drawPixelGrid(g2d);
        }
        if (jCheckBoxCoordSystem.isSelected()) {
            drawCoordinateSystem(g2d);
        }
        jPanel2D.repaint();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jComboBoxShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShapeActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBoxShape.getSelectedItem();
        CardLayout c = (CardLayout) jPanelCard.getLayout();
        if (selectedItem.equals("Đoạn thẳng") || selectedItem.equals("Hình chữ nhật")) {
            c.show(jPanelCard, "cardLineAndRect");
        } else if (selectedItem.equals("Hình tròn")) {
            c.show(jPanelCard, "cardCircle");
        } else {
            c.show(jPanelCard, "cardEllipse");
        }
    }//GEN-LAST:event_jComboBoxShapeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JCheckBox jCheckBoxCoordSystem;
    private javax.swing.JCheckBox jCheckBoxGridMode;
    private javax.swing.JComboBox<String> jComboBoxShape;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JLabel jLabelXC;
    private javax.swing.JLabel jLabelYC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2D;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel jPanelCircleCard;
    private javax.swing.JPanel jPanelEllipseCard;
    private javax.swing.JPanel jPanelLineAndRectCard;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldR;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldX2;
    private javax.swing.JTextField jTextFieldXC;
    private javax.swing.JTextField jTextFieldY1;
    private javax.swing.JTextField jTextFieldY2;
    private javax.swing.JTextField jTextFieldYC;
    // End of variables declaration//GEN-END:variables
}
