/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdhcuoiky;

import animation.Animation1;
import animation.Animation2;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import shapes2d.Line;
import shapes2d.Rectangle;
import shapes2d.Ellipse;
import shapes2d.Circle;

/**
 *
 * @author COMPUTER
 */
public class MainFrame extends javax.swing.JFrame {
    public final static int UNIT = 5;
    public static int PIXEL_SIZE = 5;
    
    // jPanel2D
    public static int maxX1, maxY1;  // 760 670 perfect
    public static int midX1, midY1;
    public BufferedImage offImage1;
    public Graphics2D g2d;
    
    // jPanel3D
    public static int maxX2, maxY2; 
    public static int midX2, midY2;
    public BufferedImage offImage2;
    public Graphics2D g3d;
    
    // Animation
    private Animation1 animation1;
    private Animation2 animation2;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        // jPanel2D
        System.out.println("2D");
        maxX1 = jPanel2D.getWidth();
        maxY1 = jPanel2D.getHeight();
        System.out.println(maxX1 + " " + maxY1);
        midX1 = maxX1 / 2;
        midY1 = maxY1 / 2;
        System.out.println(midX1 + " " + midY1);
        offImage1 = new BufferedImage(maxX1, maxY1, BufferedImage.TYPE_INT_ARGB);
        g2d = offImage1.createGraphics();
        
        // jPanel3D
        System.out.println("3D");
        maxX2 = jPanel3D.getWidth();
        maxY2 = jPanel3D.getHeight();
        System.out.println(maxX2 + " " + maxY2);
        midX2 = maxX2 / 2;
        midY2 = maxY2 / 2;
        System.out.println(midX2 + " " + midY2);
        offImage2 = new BufferedImage(maxX2, maxY2, BufferedImage.TYPE_INT_ARGB);
        g3d = offImage2.createGraphics();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2D = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(offImage1, 0, 0, null);
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxShape = new javax.swing.JComboBox<>();
        jPanelCard = new javax.swing.JPanel();
        jPanelLineAndRectCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldX1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldY1 = new javax.swing.JTextField();
        jTextFieldX2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldY2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelCircleCard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelXC = new javax.swing.JLabel();
        jTextFieldXC = new javax.swing.JTextField();
        jLabelYC = new javax.swing.JLabel();
        jTextFieldYC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelR = new javax.swing.JLabel();
        jTextFieldR = new javax.swing.JTextField();
        jPanelEllipseCard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jTextFieldXE = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldYE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldB = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonDraw = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jCheckBoxGridMode = new javax.swing.JCheckBox();
        jCheckBoxCoordSystem = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jToggleButtonAnimation1 = new javax.swing.JToggleButton();
        jToggleButtonAnimation2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3D = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(offImage2, 0, 0, null);
            }
        };
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxShape1 = new javax.swing.JComboBox<>();
        jPanelCard1 = new javax.swing.JPanel();
        jPanelLineAndRectCard1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldX3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldY3 = new javax.swing.JTextField();
        jTextFieldX4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldY4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanelCircleCard1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabelXC1 = new javax.swing.JLabel();
        jTextFieldXC1 = new javax.swing.JTextField();
        jLabelYC1 = new javax.swing.JLabel();
        jTextFieldYC1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jTextFieldR1 = new javax.swing.JTextField();
        jPanelEllipseCard1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldA1 = new javax.swing.JTextField();
        jTextFieldXE1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldYE1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldB1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButtonDraw1 = new javax.swing.JButton();
        jButtonClear1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jCheckBoxGridMode1 = new javax.swing.JCheckBox();
        jCheckBoxCoordSystem1 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2D.setPreferredSize(new java.awt.Dimension(760, 2));

        javax.swing.GroupLayout jPanel2DLayout = new javax.swing.GroupLayout(jPanel2D);
        jPanel2D.setLayout(jPanel2DLayout);
        jPanel2DLayout.setHorizontalGroup(
            jPanel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel2DLayout.setVerticalGroup(
            jPanel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chọn hình vẽ");

        jComboBoxShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đoạn thẳng", "Hình chữ nhật", "Hình tròn", "Hình Ellipse" }));
        jComboBoxShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShapeActionPerformed(evt);
            }
        });

        jPanelCard.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tọa độ điểm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("x1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("y1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("x2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("y2");

        javax.swing.GroupLayout jPanelLineAndRectCardLayout = new javax.swing.GroupLayout(jPanelLineAndRectCard);
        jPanelLineAndRectCard.setLayout(jPanelLineAndRectCardLayout);
        jPanelLineAndRectCardLayout.setHorizontalGroup(
            jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldY1))
                    .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX2))
                    .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldY2)))
                .addContainerGap())
        );
        jPanelLineAndRectCardLayout.setVerticalGroup(
            jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineAndRectCardLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelLineAndRectCard, "cardLineAndRect");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tọa độ tâm");

        jLabelXC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelXC.setText("x");

        jLabelYC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelYC.setText("y");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bán kính");

        jLabelR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelR.setText("r");

        javax.swing.GroupLayout jPanelCircleCardLayout = new javax.swing.GroupLayout(jPanelCircleCard);
        jPanelCircleCard.setLayout(jPanelCircleCardLayout);
        jPanelCircleCardLayout.setHorizontalGroup(
            jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                        .addComponent(jLabelXC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldXC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                        .addComponent(jLabelYC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldYC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                        .addComponent(jLabelR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCircleCardLayout.setVerticalGroup(
            jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircleCardLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXC)
                    .addComponent(jTextFieldXC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYC)
                    .addComponent(jTextFieldYC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR)
                    .addComponent(jTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelCircleCard, "cardCircle");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tọa độ tâm");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("a");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("x");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("y");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Bán kính");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("b");

        javax.swing.GroupLayout jPanelEllipseCardLayout = new javax.swing.GroupLayout(jPanelEllipseCard);
        jPanelEllipseCard.setLayout(jPanelEllipseCardLayout);
        jPanelEllipseCardLayout.setHorizontalGroup(
            jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldXE, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldYE, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEllipseCardLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEllipseCardLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEllipseCardLayout.setVerticalGroup(
            jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEllipseCardLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldXE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldYE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelEllipseCard, "cardEllipse");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Chức năng");

        jButtonDraw.setText("Vẽ");
        jButtonDraw.setToolTipText("");
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrawActionPerformed(evt);
            }
        });

        jButtonClear.setText("Xóa");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Chế độ");

        jCheckBoxGridMode.setText("Lưới pixels");
        jCheckBoxGridMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGridModeActionPerformed(evt);
            }
        });

        jCheckBoxCoordSystem.setText("Trục tọa độ");
        jCheckBoxCoordSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoordSystemActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Animation");

        jToggleButtonAnimation1.setText("Animation 1");
        jToggleButtonAnimation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAnimation1ActionPerformed(evt);
            }
        });

        jToggleButtonAnimation2.setText("Animation 2");
        jToggleButtonAnimation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAnimation2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxShape, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButtonDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxGridMode, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jCheckBoxCoordSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonAnimation2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonAnimation1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxShape, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDraw)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGridMode)
                    .addComponent(jCheckBoxCoordSystem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonAnimation1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonAnimation2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2D, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("2D", jPanel1);

        jPanel3D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3D.setPreferredSize(new java.awt.Dimension(760, 2));

        javax.swing.GroupLayout jPanel3DLayout = new javax.swing.GroupLayout(jPanel3D);
        jPanel3D.setLayout(jPanel3DLayout);
        jPanel3DLayout.setHorizontalGroup(
            jPanel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel3DLayout.setVerticalGroup(
            jPanel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Chọn hình vẽ");

        jComboBoxShape1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đoạn thẳng", "Hình chữ nhật", "Hình tròn", "Hình Ellipse" }));
        jComboBoxShape1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShape1ActionPerformed(evt);
            }
        });

        jPanelCard1.setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tọa độ điểm");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("x1");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("y1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("x2");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("y2");

        javax.swing.GroupLayout jPanelLineAndRectCard1Layout = new javax.swing.GroupLayout(jPanelLineAndRectCard1);
        jPanelLineAndRectCard1.setLayout(jPanelLineAndRectCard1Layout);
        jPanelLineAndRectCard1Layout.setHorizontalGroup(
            jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineAndRectCard1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(jPanelLineAndRectCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineAndRectCard1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLineAndRectCard1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldY3))
                    .addGroup(jPanelLineAndRectCard1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldX4))
                    .addGroup(jPanelLineAndRectCard1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldY4)))
                .addContainerGap())
        );
        jPanelLineAndRectCard1Layout.setVerticalGroup(
            jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineAndRectCard1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLineAndRectCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        jPanelCard1.add(jPanelLineAndRectCard1, "cardLineAndRect");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Tọa độ tâm");

        jLabelXC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelXC1.setText("x");

        jLabelYC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelYC1.setText("y");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Bán kính");

        jLabelR1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelR1.setText("r");

        javax.swing.GroupLayout jPanelCircleCard1Layout = new javax.swing.GroupLayout(jPanelCircleCard1);
        jPanelCircleCard1.setLayout(jPanelCircleCard1Layout);
        jPanelCircleCard1Layout.setHorizontalGroup(
            jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircleCard1Layout.createSequentialGroup()
                .addGroup(jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCircleCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCircleCard1Layout.createSequentialGroup()
                        .addComponent(jLabelXC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldXC1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCircleCard1Layout.createSequentialGroup()
                        .addComponent(jLabelYC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldYC1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCircleCard1Layout.createSequentialGroup()
                        .addComponent(jLabelR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldR1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelCircleCard1Layout.setVerticalGroup(
            jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCircleCard1Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXC1)
                    .addComponent(jTextFieldXC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYC1)
                    .addComponent(jTextFieldYC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCircleCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR1)
                    .addComponent(jTextFieldR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        jPanelCard1.add(jPanelCircleCard1, "cardCircle");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Tọa độ tâm");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("a");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("x");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("y");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Bán kính");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("b");

        javax.swing.GroupLayout jPanelEllipseCard1Layout = new javax.swing.GroupLayout(jPanelEllipseCard1);
        jPanelEllipseCard1.setLayout(jPanelEllipseCard1Layout);
        jPanelEllipseCard1Layout.setHorizontalGroup(
            jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEllipseCard1Layout.createSequentialGroup()
                .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEllipseCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEllipseCard1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldXE1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEllipseCard1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldYE1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEllipseCard1Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldA1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEllipseCard1Layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldB1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEllipseCard1Layout.setVerticalGroup(
            jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEllipseCard1Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldXE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldYE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEllipseCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jPanelCard1.add(jPanelEllipseCard1, "cardEllipse");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Chức năng");

        jButtonDraw1.setText("Vẽ");
        jButtonDraw1.setToolTipText("");
        jButtonDraw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDraw1ActionPerformed(evt);
            }
        });

        jButtonClear1.setText("Xóa");
        jButtonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClear1ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Chế độ");

        jCheckBoxGridMode1.setText("Lưới pixels");
        jCheckBoxGridMode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGridMode1ActionPerformed(evt);
            }
        });

        jCheckBoxCoordSystem1.setText("Trục tọa độ");
        jCheckBoxCoordSystem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoordSystem1ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Animation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxShape1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCard1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButtonDraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxGridMode1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jCheckBoxCoordSystem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxShape1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDraw1)
                    .addComponent(jButtonClear1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGridMode1)
                    .addComponent(jCheckBoxCoordSystem1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3D, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("3D", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean lackInformation() {
        String x1 = jTextFieldX1.getText();
        String y1 = jTextFieldY1.getText();
        String x2 = jTextFieldX2.getText();
        String y2 = jTextFieldY2.getText();
        return x1.equals("") || x2.equals("") || y1.equals("") || y2.equals("");
    }
    public boolean lackInformationAboutCircle() {
        String xC = jTextFieldXC.getText();
        String yC = jTextFieldYC.getText();
        String r = jTextFieldR.getText();
        return xC.equals("") || yC.equals("") || r.equals("");
    }
    public boolean lackInformationAboutEllipse() {
        String xE = jTextFieldXE.getText();
        String yE = jTextFieldYE.getText();
        String a = jTextFieldA.getText();
        String b = jTextFieldB.getText();
        return xE.equals("") || yE.equals("") || a.equals("") || b.equals("");
    }
    // Get real x from virtual coordinate system
    public static int getRealX(int virtualX) {
        return midX1 + virtualX * UNIT;
    }
    // Get real y from virtual coordinate system
    public static int getRealY(int virtualY) {
        return midY1 - virtualY * UNIT;
    }
    public static int getVirtualX(int realX) {
        return Math.round((realX - midX1) / (float) UNIT);
    }
    public static int getVirtualY(int realY) {
        return Math.round((midY1 - realY) / (float) UNIT);
    }
    public static int getRealWH(int virtualWH) {
        return virtualWH * UNIT;
    }
    public static int getVirtualWH(int realWH) {
        return Math.round(realWH / (float) UNIT);
    }
    public static int roundXY(int realXY) {
        int res = realXY;
        int temp = realXY % UNIT;
        if (temp != 0) {
            if (temp <= UNIT / 2) {
                res -= temp;
            } else {
                res += (UNIT - temp);
            }
        }
        return res;
    }
    
    public void drawPixelGrid(Graphics2D g2d) {
        g2d.setColor(Color.LIGHT_GRAY);
        for (int i = 5; i < maxX1; i += UNIT) {
            g2d.drawLine(i, 0, i, maxY1);
        }
        for (int i = 5; i < maxY1; i += UNIT) {
            g2d.drawLine(0, i, maxX1, i);
        }
    }
    public void drawCoordinateSystem(Graphics2D g2d) {
        g2d.setColor(Color.BLACK);
        g2d.drawLine(0, midY1, maxX1, midY1); // draw x axis
        g2d.drawLine(midX1, 0, midX1, maxY1); // draw y axis
        g2d.setFont(new Font("Tahoma", Font.BOLD, 12));
        g2d.drawString("X", maxX1 - 20, midY1 - 10);
        g2d.drawString("Y", midX1 + 10, 20);
        g2d.drawString("O", midX1 - 15, midY1 + 15);

//        g2d.setFont(new Font("Tahoma", Font.PLAIN, 11));
//        // danh so don vi 1, 2, 3, 4, 5... truc Ox
//        for (int i = midX1 + UNIT; i < maxX1; i += UNIT) {
//            g2d.drawLine(i, midY1 - 2, i, midY1 + 2);
//            g2d.drawString(String.valueOf((i - midX1) / 30), i - 4, midY1 + 15);
//        }
//        for (int i = midX1 - UNIT; i > 0; i -= UNIT) {
//            g2d.drawLine(i, midY1 - 2, i, midY1 + 2);
//            //            g.drawString(String.valueOf((i - midX1) / 30), i - 4, midY1 + 15);
//        }
//
//        // danh so don vi 1, 2, 3, 4, 5... truc Oy
//        for (int i = midY1 - UNIT; i > 0; i -= UNIT) {
//            g2d.drawLine(midX1 - 2, i, midX1 + 2, i);
//            g2d.drawString(String.valueOf((midY1 - i) / 28), midX1 - 20, i + 4);
//        }
//        for (int i = midY1 + UNIT; i < maxY1; i += UNIT) {
//            g2d.drawLine(midX1 - 2, i, midX1 + 2, i);
//            //            g.drawString(String.valueOf((midY1 - i) / 30), midX1 - 20, i + 4);
//        }
    }
    private void jCheckBoxGridModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGridModeActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxGridMode.isSelected()) {
            drawPixelGrid(g2d);
        } else {
            g2d.setBackground(new Color(255, 255, 255, 0));
            g2d.clearRect(0, 0, maxX1, maxY1);
            if (jCheckBoxCoordSystem.isSelected()) {
                drawCoordinateSystem(g2d);
            }
        }
        jPanel2D.repaint();
    }//GEN-LAST:event_jCheckBoxGridModeActionPerformed

    private void jCheckBoxCoordSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCoordSystemActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxCoordSystem.isSelected()) {
            drawCoordinateSystem(g2d);
        } else {
            g2d.setBackground(new Color(255, 255, 255, 0));
            g2d.clearRect(0, 0, maxX1, maxY1);
            if (jCheckBoxGridMode.isSelected()) {
                drawPixelGrid(g2d);
            }
        }
        jPanel2D.repaint();
    }//GEN-LAST:event_jCheckBoxCoordSystemActionPerformed

    private void jButtonDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrawActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBoxShape.getSelectedItem();
        g2d.setColor(Color.BLACK);
        if (selectedItem.equals("Đoạn thẳng")) {
            if (!lackInformation()) {
                int virtualX1 = Integer.parseInt(jTextFieldX1.getText());
                int virtualY1 = Integer.parseInt(jTextFieldY1.getText());
                int virtualX2 = Integer.parseInt(jTextFieldX2.getText());
                int virtualY2 = Integer.parseInt(jTextFieldY2.getText());
                new Line().draw(virtualX1, virtualY1, virtualX2, virtualY2, g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        } else if (selectedItem.equals("Hình chữ nhật")) {
            if (!lackInformation()) {
                int virtualX1 = Integer.parseInt(jTextFieldX1.getText());
                int virtualY1 = Integer.parseInt(jTextFieldY1.getText());
                int virtualX2 = Integer.parseInt(jTextFieldX2.getText());
                int virtualY2 = Integer.parseInt(jTextFieldY2.getText());
                new Rectangle().draw(new Point(virtualX1, virtualY1), new Point(virtualX2, virtualY2), g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        } else if (selectedItem.equals("Hình tròn")) {
            if (!lackInformationAboutCircle()) {
                int virtualXC = Integer.parseInt(jTextFieldXC.getText());
                int virtualYC = Integer.parseInt(jTextFieldYC.getText());
                int virtualR = Integer.parseInt(jTextFieldR.getText());
                new Circle().draw(virtualXC, virtualYC, virtualR, g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        } else if (selectedItem.equals("Hình Ellipse")) {
            if (!lackInformationAboutEllipse()) {
                int virtualXE = Integer.parseInt(jTextFieldXE.getText());
                int virtualYE = Integer.parseInt(jTextFieldYE.getText());
                int virtualA = Integer.parseInt(jTextFieldA.getText());
                int virtualB = Integer.parseInt(jTextFieldB.getText());
                new Ellipse().draw(virtualXE, virtualYE, virtualA, virtualB, g2d);
                jPanel2D.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống tọa độ!");
            }
        }
    }//GEN-LAST:event_jButtonDrawActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        g2d.setBackground(new Color(255, 255, 255, 0));
        g2d.clearRect(0, 0, maxX1, maxY1);
        if (jCheckBoxGridMode.isSelected()) {
            drawPixelGrid(g2d);
        }
        if (jCheckBoxCoordSystem.isSelected()) {
            drawCoordinateSystem(g2d);
        }
        jPanel2D.repaint();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jComboBoxShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShapeActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBoxShape.getSelectedItem();
        CardLayout c = (CardLayout) jPanelCard.getLayout();
        if (selectedItem.equals("Đoạn thẳng") || selectedItem.equals("Hình chữ nhật")) {
            c.show(jPanelCard, "cardLineAndRect");
        } else if (selectedItem.equals("Hình tròn")) {
            c.show(jPanelCard, "cardCircle");
        } else {
            c.show(jPanelCard, "cardEllipse");
        }
    }//GEN-LAST:event_jComboBoxShapeActionPerformed

    private void jToggleButtonAnimation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAnimation1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonAnimation1.isSelected()) {
            try {
                animation1 = new Animation1(jPanel2D, g2d);
            } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            animation1.timer.stop();
            animation1.clip.stop();
            MainFrame.PIXEL_SIZE = 5;
            g2d.setBackground(new Color(255, 255, 255, 0));
            g2d.clearRect(0, 0, maxX1, maxY1);
            jPanel2D.repaint();
        }
    }//GEN-LAST:event_jToggleButtonAnimation1ActionPerformed

    private void jComboBoxShape1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShape1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxShape1ActionPerformed

    private void jButtonDraw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDraw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDraw1ActionPerformed

    private void jButtonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClear1ActionPerformed

    private void jCheckBoxGridMode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGridMode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxGridMode1ActionPerformed

    private void jCheckBoxCoordSystem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCoordSystem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCoordSystem1ActionPerformed

    private void jToggleButtonAnimation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAnimation2ActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonAnimation2.isSelected()) {
            try {
                animation2 = new Animation2(jPanel2D, g2d);
            } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            animation2.timer.stop();
            animation2.clip.stop();
            MainFrame.PIXEL_SIZE = 5;
            g2d.setBackground(new Color(255, 255, 255, 0));
            g2d.clearRect(0, 0, maxX1, maxY1);
            jPanel2D.repaint();
        }
    }//GEN-LAST:event_jToggleButtonAnimation2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClear1;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JButton jButtonDraw1;
    private javax.swing.JCheckBox jCheckBoxCoordSystem;
    private javax.swing.JCheckBox jCheckBoxCoordSystem1;
    private javax.swing.JCheckBox jCheckBoxGridMode;
    private javax.swing.JCheckBox jCheckBoxGridMode1;
    private javax.swing.JComboBox<String> jComboBoxShape;
    private javax.swing.JComboBox<String> jComboBoxShape1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JLabel jLabelR1;
    private javax.swing.JLabel jLabelXC;
    private javax.swing.JLabel jLabelXC1;
    private javax.swing.JLabel jLabelYC;
    private javax.swing.JLabel jLabelYC1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2D;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3D;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel jPanelCard1;
    private javax.swing.JPanel jPanelCircleCard;
    private javax.swing.JPanel jPanelCircleCard1;
    private javax.swing.JPanel jPanelEllipseCard;
    private javax.swing.JPanel jPanelEllipseCard1;
    private javax.swing.JPanel jPanelLineAndRectCard;
    private javax.swing.JPanel jPanelLineAndRectCard1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldA1;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldB1;
    private javax.swing.JTextField jTextFieldR;
    private javax.swing.JTextField jTextFieldR1;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldX2;
    private javax.swing.JTextField jTextFieldX3;
    private javax.swing.JTextField jTextFieldX4;
    private javax.swing.JTextField jTextFieldXC;
    private javax.swing.JTextField jTextFieldXC1;
    private javax.swing.JTextField jTextFieldXE;
    private javax.swing.JTextField jTextFieldXE1;
    private javax.swing.JTextField jTextFieldY1;
    private javax.swing.JTextField jTextFieldY2;
    private javax.swing.JTextField jTextFieldY3;
    private javax.swing.JTextField jTextFieldY4;
    private javax.swing.JTextField jTextFieldYC;
    private javax.swing.JTextField jTextFieldYC1;
    private javax.swing.JTextField jTextFieldYE;
    private javax.swing.JTextField jTextFieldYE1;
    private javax.swing.JToggleButton jToggleButtonAnimation1;
    private javax.swing.JToggleButton jToggleButtonAnimation2;
    // End of variables declaration//GEN-END:variables
}
